{"repo_id": "Pylons_waitress_377", "bugs": [{"description": "Potential negative value assignment to self.remain in FileBasedBuffer constructor. If from_file.tell() returns a position less than read_pos, the calculation 'file.tell() - read_pos' could result in a negative value being assigned to self.remain, which should always be non-negative as it represents remaining bytes in the buffer.", "file": "src/waitress/buffers.py", "line": 40}, {"description": "Race condition in cancel() method. The method sets self.requests = [] without acquiring the requests_lock, which could lead to race conditions with other threads that are accessing or modifying the requests list while holding the lock.", "file": "src/waitress/channel.py", "line": 517}, {"description": "Potential deadlock in _flush_outbufs_below_high_watermark(). The method acquires outbuf_lock with 'with self.outbuf_lock:' at line 394, but this method is called from write_soon() which already holds the same lock, potentially causing a deadlock since threading.Condition is not reentrant by default.", "file": "src/waitress/channel.py", "line": 394}, {"description": "AttributeError on non-Windows systems. The code references errno.WSAEADDRINUSE which is a Windows-specific error code that doesn't exist on POSIX systems. This will cause an AttributeError when the code runs on Linux/Unix systems, even though this is in a Windows-only code path.", "file": "src/waitress/trigger.py", "line": 176}, {"description": "AttributeError in Python versions before 3.5. The code uses os.set_blocking(fd, False) which was only introduced in Python 3.5. This will cause an AttributeError in earlier Python versions, causing the file_dispatcher initialization to fail.", "file": "src/waitress/wasyncore.py", "line": 686}, {"description": "AttributeError in Python 2.7. The code uses __qualname__ attribute which doesn't exist in Python 2.7, only in Python 3.3+. This will cause an AttributeError when the __repr__ method is called on dispatcher objects in Python 2.7.", "file": "src/waitress/wasyncore.py", "line": 321}, {"description": "NameError in Python 2.7. The code references ResourceWarning which doesn't exist in Python 2.7, only in Python 3.2+. This will cause a NameError when the file_wrapper.__del__ method is called in Python 2.7.", "file": "src/waitress/wasyncore.py", "line": 647}], "updated_files": {}}