{"repo_id": "django_django_16485", "bugs": [{"description": "The get_exception_info function in django/template/backends/jinja2.py assumes that the exception object has lineno and source attributes, which may not always be the case. This could lead to an AttributeError if the exception object does not have these attributes.", "file": "django/template/backends/jinja2.py", "line": 93}], "updated_files": {}}